AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: ruby3.2
      CodeUri: "./"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
  AppUrl:
    Value: !Sub "https://${Function}.execute-api.${AWS::Region}.amazonaws.com/"